WIP: Modules for ALB & NLB.
skyscrapers/terraform-loadbalancers pull request #13
Opened 2017-12-18 17:06 UTC by ringods

*NOTE:* Work in progress. This PR should not be submitted to the PR queue in #technical

Fix for: https://github.com/skyscrapers/core/issues/12

* Module `alb_listener` between `alb` and `alb_rule_target`. Makes it easier to manage target groups, listeners and listener rules. 

TODO:
* Add support for registering additional certificates on an LB listener from the `alb_rule_target` module. While it is supported in the console/cli/sdk, it is not yet integrated in terraform. Request was filed as https://github.com/terraform-providers/terraform-provider-aws/issues/1853 and the corresponding PR is https://github.com/terraform-providers/terraform-provider-aws/pull/2686

2017-12-19 16:02 UTC, MattiasGees approved these changes
Look ok, for me this is a major version bump

2017-12-19 16:12 UTC, venturel approved these changes
It looks good also to me. I agree with Mattias on the major version bump

2017-12-19 16:13 UTC, SamClinckspoor reviewed
is there any value in the nlb and alb parts? I can understand for the listener but the main aws_lb modules don't do much

2017-12-19 16:16 UTC, SamClinckspoor requested changes

2017-12-19 16:16 UTC, SamClinckspoor commented on nlb/main.tf
> +  name                       = "${var.project}-${var.environment}-${var.name}-nlb"
please use `name_prefix`

2017-12-19 16:16 UTC, SamClinckspoor commented on alb/main.tf
>    name                       = "${var.project}-${var.environment}-${var.name}-alb"
please use `name_prefix`

2017-12-19 16:16 UTC, SamClinckspoor commented on nlb/sg.tf
> +  name        = "sg_alb_${var.project}_${var.environment}_${var.name}"
please use `name_prefix`

2017-12-19 17:03 UTC, ringods commented
@SamClinckspoor the reason is cost. Contrary to an ELB, we will no longer set up a application or network load balancer per application. The LB will be a shared resource.

For an application load balancer, we add HTTP and/or HTTPS listeners, then add `aws_lb_listener_rule` with different target groups to route to different hosts.

For a network load balancer, we add additional port specific listeners.

2017-12-20 08:54 UTC, SamClinckspoor commented
I mean, what value does the module bring. As far as I can tell the `alb` and `nlb` don't provide a lot of abstraction to make it easier to use compared to using the resource instead of the module

2017-12-20 08:54 UTC, SamClinckspoor approved these changes

2017-12-20 09:00 UTC, ringods commented
It's debatable indeed, but having the modules (lb + sg) makes the setup consistent module wise.

2017-12-20 09:27 UTC, merged